# Use postgres/example user/password credentials
# Activate Docker Image -> docker-compose -f Documents/IdeaProjects/spring-examples/spring-datajpa-postgresql/src/main/resources/docker-compose.yml up -d
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: myPassword

