# Use root/example as user/password credentials
#Activate Docker Image -> docker-compose -f Documents/IdeaProjects/spring-examples/spring-boot-aop/src/main/resources/docker-compose.yml up -d
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example