# Use root/example as User/password credentials
#Activate Docker Image -> docker-compose -f Documents/IdeaProjects/spring-examples/spring-boot-rabbitmq/src/main/resources/docker-compose.yml up -d
version: '3.1'
services:
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=akinogrence
      - RABBITMQ_DEFAULT_PASS=akinogrence